build: false

environment: 
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
      
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64
      
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
      
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64

init: 
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install: 
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%" 
  - python --version
  - python -c "import sys,platform,struct;print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"
  - conda config --set always_yes yes --set changeps1 no 
  - conda update -q conda 
  - conda info -a 
  - "conda create -q -n test-environment 
  python=%PYTHON_VERSION% numpy pandas scipy matplotlib pytest" 
  - activate test-environment 
  - conda install libpython m2w64-toolchain cython
  - echo [build] > %CONDA_PREFIX%\Lib\distutils\distutils.cfg
  - echo compiler = mingw32 >> %CONDA_PREFIX%\Lib\distutils\distutils.cfg
  - python setup.py install

test_script: 
  - pytest .

after_test:
  # If tests are successful, create binary packages for the project.
  - python setup.py bdist_wheel"
  - python setup.py bdist_wininst"
  - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*
